WTF_CSRF_ENABLED = False
WTF_CSRF_SECRET_KEY = 'tp)xP9D0ArWdtQJXkHPQAB0B22a(6E'
SECRET_KEY = 'tp)xP9D0ArWdtQJXkHPQAB0B22a(6E'
SQLALCHEMY_POOL_RECYCLE = 100
SQLALCHEMY_POOL_TIMEOUT = 20
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://selor:selor@localhost/selor'
SQLALCHEMY_TRACK_MODIFICATIONS = False
